/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kargo;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author semih
 */
public class StaffLogin extends javax.swing.JFrame {
    public static Database db;
    private static ArrayList<String[]> packages;
    /**
     * Creates new form StaffLogin
     * @param db
     */
    public StaffLogin(Database db) {
        initComponents();
        StaffLogin.db = db;
        DefaultTableModel model = (DefaultTableModel) cargoTable.getModel();
        packages = StaffLogin.db.getCargo();
        for (String[] strArr : packages) {
            model.addRow((Object[])strArr);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cargoTable = new javax.swing.JTable();
        tableSName = new javax.swing.JTextField();
        tableFragile = new javax.swing.JCheckBox();
        tableSNumber = new javax.swing.JTextField();
        tableSAddress = new javax.swing.JTextField();
        tableRName = new javax.swing.JTextField();
        tableRNumber = new javax.swing.JTextField();
        tableAddressDelivered = new javax.swing.JTextField();
        tableUpdate = new javax.swing.JButton();
        tableArrived = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tableMessage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cargoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Track No", "Sender Name", "Sender Number", "Sender Address", "Recipient Name", "Recipient Number", "Address to be Delivered", "Fragile Package", "State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cargoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cargoTable);

        tableSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableSNameActionPerformed(evt);
            }
        });

        tableFragile.setText("Fragile");

        tableUpdate.setText("Update");
        tableUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableUpdateActionPerformed(evt);
            }
        });

        tableArrived.setText("Arrived");
        tableArrived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableArrivedActionPerformed(evt);
            }
        });

        jLabel1.setText("Sender Name");

        jLabel2.setText("Sender Number");

        jLabel3.setText("Sender Address");

        jLabel4.setText("Recipient Name");

        jLabel5.setText("Recipient Number");

        jLabel6.setText("Addres to be Delivered");

        tableMessage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tableMessage.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setText("State");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(tableMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(tableUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tableArrived, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tableSName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tableSNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tableSAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tableRName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tableRNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableAddressDelivered, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableFragile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableFragile)
                    .addComponent(tableSNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableSAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableRName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableRNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableAddressDelivered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tableUpdate)
                            .addComponent(tableArrived)))
                    .addComponent(tableMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableUpdateActionPerformed
        tableMessage.setText("");
        
        DefaultTableModel model = (DefaultTableModel)cargoTable.getModel();
        int row = cargoTable.getSelectedRow();
        if(row == -1){
            if(cargoTable.getRowCount() == 0){
                tableMessage.setText("Table is Empty");
            }
            else{
                tableMessage.setText("Please Select a Row");
            }
        }
        else{
            model.setValueAt(tableSName.getText(), row, 1);
            model.setValueAt(tableSNumber.getText(), row, 2);
            model.setValueAt(tableSAddress.getText(), row, 3);
            model.setValueAt(tableRName.getText(), row, 4);
            model.setValueAt(tableRNumber.getText(), row, 5);
            model.setValueAt(tableAddressDelivered.getText(), row, 6);
            model.setValueAt(state.getText(), row, 8);
            if(tableFragile.isSelected())
                model.setValueAt("True", row, 7);
            else
                model.setValueAt("False", row, 7);
            
            tableMessage.setText("Succesfully Updated");
            String str;
            if(tableFragile.isSelected()){
                str = "true";
            }
            else{
                str = "false";
            }
            
            db.updateCargo(model.getValueAt(row, 0).toString(),tableSName.getText(),
            tableSNumber.getText(),tableSAddress.getText(),tableRName.getText(),
            tableRNumber.getText(),tableAddressDelivered.getText(),str,state.getText());
        }
    }//GEN-LAST:event_tableUpdateActionPerformed
    
    public void addItemtoTable(Object[] info){
        DefaultTableModel model = (DefaultTableModel) cargoTable.getModel();
        model.addRow(info);
    }
    
    
    private void cargoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargoTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) cargoTable.getModel();
        int row = cargoTable.getSelectedRow();
        boolean b;
        if(model.getValueAt(row, 7).toString().equals("true")){
            b = true;
        }
        else{
            b = false;
        }
        
        tableSName.setText(model.getValueAt(row, 1).toString());
        tableSNumber.setText(model.getValueAt(row, 2).toString());
        tableSAddress.setText(model.getValueAt(row, 3).toString());
        tableRName.setText(model.getValueAt(row, 4).toString());
        tableRNumber.setText(model.getValueAt(row, 5).toString());
        tableAddressDelivered.setText(model.getValueAt(row, 6).toString()); 
        tableFragile.setSelected(b);
        
    }//GEN-LAST:event_cargoTableMouseClicked

    private void tableArrivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableArrivedActionPerformed
        DefaultTableModel model = (DefaultTableModel) cargoTable.getModel();
        int row = cargoTable.getSelectedRow();
        if(row == -1){
            if(cargoTable.getRowCount() == 0){
                tableMessage.setText("Table is Empty");
            }
            else{
                tableMessage.setText("Please Select a Row");
            } 
        }
        else{
            db.packageArrived(model.getValueAt(row, 0).toString());
            model.removeRow(row);
        }
    }//GEN-LAST:event_tableArrivedActionPerformed

    private void tableSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableSNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffLogin(db).setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cargoTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField state;
    private javax.swing.JTextField tableAddressDelivered;
    private javax.swing.JButton tableArrived;
    private javax.swing.JCheckBox tableFragile;
    private javax.swing.JLabel tableMessage;
    private javax.swing.JTextField tableRName;
    private javax.swing.JTextField tableRNumber;
    private javax.swing.JTextField tableSAddress;
    private javax.swing.JTextField tableSName;
    private javax.swing.JTextField tableSNumber;
    private javax.swing.JButton tableUpdate;
    // End of variables declaration//GEN-END:variables

}
